name: CI

on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch: # allows you to trigger the workflow run manually

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        python-version: [ "3.11", "3.12" ]
        resolution: [ "highest", "lowest-direct" ]
    steps:
    - uses: actions/checkout@v4

    - name: Set up uv and caching
      uses: astral-sh/setup-uv@v6
      with:
        enable-cache: true
        cache-suffix: "${{ matrix.os }}-${{ matrix.python-version }}-${{ matrix.resolution }}"
        cache-dependency-glob: "pyproject.toml"
        version: "0.12.7"

    - name: Create venv
      run: |
        uv venv --python ${{ matrix.python-version }}

    # deliberately resolved without the lockfile: as a library, we want to know that we
    # work with the whole range of dependency versions we allow
    - name: Install ${{ matrix.resolution }} dependencies
      run: |
        uv pip install --resolution ${{ matrix.resolution }} .[test]

    - name: Test with pytest
      run: |
        uv run --no-sync pytest --xdoc --cov=primap2 --cov-report=xml --junitxml=junit.xml -o junit_family=legacy

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        files: ./coverage.xml
        token: ${{ secrets.CODECOV_TOKEN }}

    - name: Upload test results to Codecov
      if: ${{ !cancelled() }}
      uses: codecov/test-results-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
